name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # 每月1号运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install Chromium aiofiles requests

      - name: Install Chromium Browsers  # 安装浏览器
        run: |
          Chromium install

      - name: 运行登录脚本
        env:
          my_username: ${{ secrets.username }}
          my_password: ${{ secrets.password }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          python my_script.py
